{% set name = "paralleltask" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Paralleltask-{{ version }}.tar.gz
  sha256: f00945e2bd5b6aff9cdc48fbd92aa7b48d23bb530d7f6643ac966fea11a7a9d5

build:
  entry_points:
    - paralleltask=paralleltask.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - psutil
    - python >=3.6

test:
  imports:
    - paralleltask
  commands:
    - pip check
    - paralleltask --help
  requires:
    - pip

about:
  home: https://github.com/moold/ParallelTask
  summary: A simple and lightweight parallel task engine
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpetit3
