{% set name = "paralleltask" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Paralleltask-{{ version }}.tar.gz
  sha256: eb0c78413ceadfa94f4cd7ccc64e515544f0c11cded9a4b4c3bec00d6693fbda

build:
  entry_points:
    - paralleltask=paralleltask.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - psutil
    - python >=3.6

test:
  imports:
    - paralleltask
  commands:
    - pip check
    - paralleltask --help
  requires:
    - pip

about:
  home: https://github.com/moold/ParallelTask
  summary: A simple and lightweight parallel task engine
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpetit3
